### ISSUE TITLE
How to choose perplexity?

### ISSUE THREAD

**Issue by nhuhoa** [immunogenomics/LISI#1]
Dear Korsunsky et al, 
Thanks for very nice work. The toolbox LISI runs well in R 3.5 and 3.6 and give the good output. 

I just have a question about the perplexity that you use to compute LISI. 

In the Harmony manuscript, you used a fixed perplexity = 30. Is there any reason why you use this value? Is this because this value is also the default value of tsne visualization? Based on your experiments, do you have any recommendation for small dataset (<100 cells per cell type cluster in each batch), medium size (<1000 cells per cell type cluster), and large size (> 1000 cells)? When I tested on small dataset, I tried to use different perplexities in the range of [10, 150], step = 10, and recorded the values of iLISI and cLISI. The output showed that there are a trade-off of batch mixing and cel type mixing. When perplexity increase, batch mixing increase and cell type mixing decrease. It is difficult to define a fixed perplexity.  

Thanks a lot, 
Best, 
Hoa Tran

**Comment by slowkow** [comment]
Sorry, I think we never answered this question because it does not have a clear answer. We should always look carefully at the data and be thoughtful about interpreting any statistics.
