### ISSUE TITLE
Some questions about LISI rate except batch specific types

### ISSUE THREAD

**Issue by HelloWorldLTY** [immunogenomics/LISI#10]
If I have batch specific cell types dataset in my scRNA-seq, is it still reasonable to calculate the Lisi rate without removing the batch specific data? Thanks.

**Comment by slowkow** [comment]
The `compute_lisi()` function in this package will find the nearest neighbors for each cell, and then compute an Inverse Simpson Index for that Local neighborhood of cells (hence the name LISI). We should always be thoughtful when we interpret any statistic.

It is a great idea to read the code line-by-line to understand exactly what is happening: https://github.com/immunogenomics/LISI/blob/master/R/utils.R
