### ISSUE TITLE
Create tag to simplify conda packaging

### ISSUE THREAD

**Issue by tdido** [immunogenomics/LISI#11]
Hello.

We'd like to package your software into a conda package, and for this we'd need a version tag that generates a release. Would you be willing to create one?

**Comment by slowkow** [comment]
Sure!

**Comment by slowkow** [comment]
Thanks for letting us know. Hope this works for you: https://github.com/immunogenomics/LISI/releases/tag/v1.0

**Comment by tdido** [comment]
Fantastic, thank you. I'll eventually upload the package to the bioconda repository and create a issue with details in case you want to add the alternative installation method to the docs.
