### ISSUE TITLE
LISI on cluster Identities

### ISSUE THREAD

**Issue by loverend** [immunogenomics/LISI#4]
Hi - looking forward to playing around with LISI and Integration. 
Quick question - would calculating a cLISI score on cluster identities which have been assigned through say louvain clustering be meaningful given the input of pcas to both methdos? Or should I just stick with an iLISI on the orig.identity of the cell lines I have integrated. 

For calculating these two different metrics is it purely dependant on the variable you input, but calculated in the same way as in the tutorial section? e.g. orig.ident = iLISI cell type assigment = cISI, or is there anything else to be aware of? 

Also would there be any way of assessing if a cluster within my mixed data set is poorly mixed by comparison to the rest of the data set beyond just calculating a mean iLISI per cluster? I do have some sample specific clusters and want to ensure these are preserved post-integration so it would be quite nice to show a difference in iLISI between these. 

Thanks!
Lauren

**Comment by slowkow** [comment]
You are right that there is only one algorithm for computing the Local Inverse Simpson Index (LISI) scores.

The names "iLISI" (integration LISI) and "cLISI" (cluster LISI) are just labels intended to distinguish two different applications of LISI.

I was also confused by this the first time I encountered the terms. In my opinion, these labels are not helpful and I'd prefer a more verbose description like "LISI of datasets" or "LISI of batches" instead of "iLISI".

We could apply LISI to any categorical variable to estimate how many categories are near each cell.

I believe it is reasonable to compute a mean LISI per cluster, and to show that some clusters have higher or lower LISI scores than others.

**Comment by loverend** [comment]
> You are right that there is only one algorithm for computing the Local Inverse Simpson Index (LISI) scores.
> 
> The names "iLISI" (integration LISI) and "cLISI" (cluster LISI) are just labels intended to distinguish two different applications of LISI.
> 
> I was also confused by this the first time I encountered the terms. In my opinion, these labels are not helpful and I'd prefer a more verbose description like "LISI of datasets" or "LISI of batches" instead of "iLISI".
> 
> We could apply LISI to any categorical variable to estimate how many categories are near each cell.
> 
> I believe it is reasonable to compute a mean LISI per cluster, and to show that some clusters have higher or lower LISI scores than others.

Thank you for your helpful response - very reassuring. Would you mind answering one other question? I have noted that the mean of my LISI scores is often > 2 . For context I integrated  2 samples from the the same cell line but different donors and also one sample which contained a mix of the same two cell lines (but the identity of each cell wasn't computed) and it wasn't clear to me if we would expect the LISI score to be bounded by 2 which it looks like they are in the Harmony paper so I am wondering if I am getting an odd score because im calculating the LISI score on 3 categories rather than taking into account the mixed population is a mixture of the two. Thankyou!

**Comment by slowkow** [comment]
Hi Lauren,

Thanks for the question. Could I ask if you might be able to share a bit more information? Maybe a table similar to the one below might help.

Here's an example copied from the Harmony paper. I hope it helps to clarify the situation.

| Dataset        | Jurkat | 293T |
| ---            | ---    | ---  |
| 1. Pure Jurkat | 3255   | 0    |
| 2. Pure 293T   | 0      | 2859 |
| 3. 50/50 Mix   | 1799   | 1565 |

```r
#' Inverse Simpson Index (ISI)
#' https://en.wikipedia.org/wiki/Diversity_index#Inverse_Simpson_index
#' @param n A vector of counts.
isi <- function(n) {
  p <- n / sum(n)
  1 / sum(p ^ 2)
}
```

```r
# ISI for 3 datasets
n <- c(3255, 2859, 1799 + 1565)
round(isi(n), 2)
#> [1] 2.99

# ISI for 2 cell types
n <- c(3255 + 1799, 2859 + 1565)
round(isi(n), 2)
#> [1] 1.99
```

In the Jurkat neighborhood, we should see 2 datasets. However, they are not balanced, so we expect 1.85 datasets in the Jurkat neighborhood:

```r
n1 <- c(3255, 1799)
round(isi(n1), 2)
#> [1] 1.85
```

In the 293T neighborhood, we should see 2 datasets. However, they are not balanced, so we expect 1.84 datasets in the 293T neighborhood:

```r
n2 <- c(2859, 1565)
round(isi(n2), 2)
#> [1] 1.84
```

Overall, we expect the weighted average of the two ISI scores:

```r
( isi(n1) * sum(n1) + isi(n2) * sum(n2) ) / sum(n1, n2)
#> [1] 1.844699
```
