### ISSUE TITLE
The calculation of the Gaussian kernel-based distributions of neighborhoods and the perplexity issue

### ISSUE THREAD

**Issue by Van1yu3** [immunogenomics/LISI#7]
Hi, I'm confused by the inconsistency of how the LISI code runs and what the Harmony paper describes. So I'm here to ask whether I have a huge misunderstanding on either the code or the paper.

1. The paper says that 

> To be sensitive to local diversity, we build Gaussian kernel-based distributions of neighborhoods. This gives distance-based weights to cells in the neighborhood.

However, I find that the [source code](https://github.com/immunogenomics/LISI/blob/a917556310d8d2c66833dcc35aa3d0f4d1b6e0f4/R/utils.R#L55) in this repo just utilizes the `nn2` function in the `RANN` R package, without any preprocessing procedure on the data or the distance.

2. The paper describes that using a fixed perplexity in the LISI has been shown to be a smoother function than fixing the number of neighbors. But I find that the code sets `k=perplexity*3` in the `nn2` function, which seems like the perplexity is somewhat equivalent to the number of neighbors.

Could you please help me out of these confusions? Thanks a lot!

**Comment by ilyakorsunsky** [comment]
Hi @Van1yu3, thanks for checking out the code! The weights of the neighbors are computed to a specified perplexity in the compute_simpson_index function in the src/ folder

**Comment by Van1yu3** [comment]
Hi @ilyakorsunsky , thanks for your reply! 

May I know the technical details of calculating the Gaussian kernel-based distributions of neighborhoods? I could not find any detail about it in the paper. Any related reference is appreciated.

**Comment by ilyakorsunsky** [comment]
Sure! The procedure is identical to the one used in tSNE, so the original van der Maaten and Hinton paper is a good source: https://www.jmlr.org/papers/volume9/vandermaaten08a/vandermaaten08a.pdf?fbclid=IwAR0Bgg1eA5TFmqOZeCQXsIoL6PKrVXUFaskUKtg6yBhVXAFFvZA6yQiYx-M
