### ISSUE TITLE
Meet error when I use LISI to test my model

### ISSUE THREAD

**Issue by HelloWorldLTY** [immunogenomics/LISI#8]
When I run the code, I will face such errors:
![image](https://user-images.githubusercontent.com/43333475/118763316-35b5f380-b8aa-11eb-9c70-665b3a82f00e.png)

I also give similar input for kBET methods, and I get the results I intend to get. 
![image](https://user-images.githubusercontent.com/43333475/118763347-45cdd300-b8aa-11eb-931f-61c301b664ec.png)

Is there anything wrong? Thanks

**Comment by slowkow** [comment]
Please consider reading [the documentation](https://github.com/immunogenomics/LISI/blob/28ff0eea0160933a12efc98ae9c881c353390e72/R/utils.R) for the function:

```
#' Compute Local Inverse Simpson's Index (LISI)
#' 
#' Use this function to compute LISI scores of one or more labels. 
#' 
#' @param X A matrix with cells (rows) and features (columns).
#' @param meta_data A data frame with one row per cell. 
#' @param label_colnames Which variables to compute LISI for. 
#' @param perplexity The effective number of each cell's neighbors.
#' @param nn_eps Error bound for nearest neighbor search with \code{RANN:nn2()}.
#' Default of 0.0 implies exact nearest neighbor search.
```

Then, confirm that the following statements are true:

1. `new_data_l` is a matrix with cells (rows) and features (columns)
2. `labels[[1]]` is a data frame with one row per cell.
3. `c('label1', 'label2')` is a vector with names of columns in the data frame `labels[[1]]`.
