### ISSUE TITLE
question about cLISI

### ISSUE THREAD

**Issue by wiredosprout** [immunogenomics/LISI#9]
I noticed that in your manuscript figure 2b, cLISI means cell type LISI metric.

What I understand here is:if I want to compute this cell type LISI metric, then I have to know the real cell type first.

However, in my situation, there is no way for me to know this real cell type information, so I can do only regular batch version LISI metric right? But I can do it for each cluster, and see what are the corresponding batch LISI in each cluster.

Are my understanding correct?

Thx a lot!

**Comment by slowkow** [comment]
If we are willing to accept the assumption that a *cluster label* represents the "cell types" in our dataset, then we can compute LISI on that label and call it a "cell type LISI."
